import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { APIClientProvider } from "~/providers/APIClientProvider";
import Header from "~/components/ui/Header";
import { AuthClientProvider } from "~/providers/authProvider";
import { QueryProviderClient } from "~/providers/QueryProviderClient";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-gradient-to-br from-gray-900 to-black">
        <QueryProviderClient>
          <APIClientProvider>
            <AuthClientProvider>
              <Header />
              {children}
            </AuthClientProvider>
          </APIClientProvider>
        </QueryProviderClient>
      </body>
    </html>
  );
}
